=== floatcam/blog/publications/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "date": {
      "type": "string",
      "format": "date-time",
      "description": "The publication date, example: June 23rd, 2023"
    },
    "slug": {
      "type": "string",
      "description": "The URL-friendly string that identifies the publication"
    },
    "title": {
      "type": "string",
      "description": "The title of the publication"
    },
    "author": {
      "type": "string",
      "description": "The author of the publication"
    },
    "duration": {
      "type": "string",
      "description": "An estimate of how long it will take to read the publication"
    },
    "cover": {
      "type": "string",
      "format": "uri",
      "description": "A URL to an image that represents the publication. This can also be a relative path to an image in the same directory as the publication"
    }
  },
  "required": ["date", "slug", "title", "author", "duration", "cover"]
}

=== floatcam/blog/publications/index.json
[
  {
    "date": "June 24th, 2023",
    "slug": "real-time-media-collection-from-users-the-new-frontier-in-user-generated-content",
    "title": "Real-time Media Collection from Users: The New Frontier in User Generated Content",
    "author": "Simon Peter Damian",
    "duration": "3 minutes read",
    "cover": "featured.jpg"
  },
  {
    "date": "June 23rd, 2023",
    "slug": "the-new-floatcam-evolving-to-better-serve-you",
    "title": "The New floatcam: Evolving to Better Serve You",
    "author": "Simon Peter Damian",
    "duration": "3 minutes read",
    "cover": "featured.jpg"
  }
]
